{
    id: 1,
    image: "/items/paso.jpg",
    title: "Paso",
    price: 99.9,
  },
  {
    id: 2,
    image: "/items/plato.jpg",
    title: "Plato",
    price: 57.2,
  },
  {
    id: 3,
    image: "/items/balisong.jpg",
    title: "Balisong",
    price: 346.6,
  },
  {
    id: 4,
    image: "/items/kangkongchips.jpg",
    title: "Kangkong Chips",
    price: 130,
  },
  {
    id: 5,
    image: "/items/pamaypay.jpg",
    title: "Pamaypay",
    price: 36.8,
  },
  {
    id: 6,
    image: "/items/parol.jpg",
    title: "Parol",
    price: 350.4,
  },
  {
    id: 1,
    image: "/items/paso.jpg",
    title: "Paso",
    price: 99.9,
  },
  {
    id: 2,
    image: "/items/plato.jpg",
    title: "Plato",
    price: 57.2,
  },
  {
    id: 3,
    image: "/items/balisong.jpg",
    title: "Balisong",
    price: 346.6,
  },
  {
    id: 4,
    image: "/items/kangkongchips.jpg",
    title: "Kangkong Chips",
    price: 19.99,
  },
  {
    id: 5,
    image: "/items/pamaypay.jpg",
    title: "Pamaypay",
    price: 36.8,
  },
  {
    id: 6,
    image: "/items/parol.jpg",
    title: "Parol",
    price: 350.4,
  },